services:
  - type: web
    name: bloxyspin-api
    env: node
    plan: starter
    rootDir: api
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*" # You should restrict this to your frontend domain in production 